let knockJokes = [
  "Knock knock. Who's there? Says. Says who? Says me, that's who!",
  "Knock knock. Who's there? Gouda. Gouda who? Gouda knock knock jokes, don't you think?'",
  "Knock knock. Who's there? Honeydew. Honeydew who? Honeydew you wanna dance?",
  "Knock knock. Who's there? Europe. Europe who? No, YOU'RE a poo!",
  "Knock knock. Who's there? Omelette. Omelette who? Omelette you finish.",
  "Knock knock. Who's there? You. You who? You hoo, anybody home?",
  "Knock knock. Who's there? Ruff ruff. Ruff ruff who? Who let the dogs out? I heard barking!",
  "Knock knock. Who's there? Ray D. Ray D. who? Ray D or not, here I come.",
  "Knock knock. Who's there? Linda. Linda who? Linda Hand, will ya? Mine is tired from knocking.",
  "Knock knock. Who's there? Sue. Sue who? I'll see you in court!",
  "Knock knock. Who's there? Bacon. Bacon who? Baking some cookies in there? It smells delicious!",
  "Knock knock. Who's there? Roach. Roach who? Roach you an email last week and I'm still waiting for a response.",
  "Knock knock. Who's there? Ida. Ida who? It's pronounced Ida-ho, and the state capital is Boise.",
  "Knock knock. Who's there? Jimmy. Jimmy who? Jimmy crack corn and I don't care!",
  "Knock knock. Who's there? I am. I am who? I am who is knocking. Who are you?",
  "Knock knock. Who's there? Rhonda. Rhonda who? Is this the rendezvous point? I was told to knock twice.",
  "Knock knock. Who's there? Art. Art who? R2D2 is my favorite droid in Star Wars.",
  "Knock knock. Who's there? Weekend. Weekend who? Weekend do anything we want!",
  "Knock knock. Who's there? I. O. I. O. who? Me. When are you paying me back?",
  "Knock knock. Who's there? Taco. Taco who? Taco to you later. It's taking too long for you to open the door.",
  "Knock knock. Who's there? Hawaii. Hawaii who? I'm fine, Hawaii you?",
  "Knock knock. Who's there? Voodoo. Voodoo who? Voodoo you think you are, asking me so many questions?",
  "Knock knock. Who's there? Nana. Nana who? Nana your business.",
  "Knock knock. Who's there? Hatch. Hatch who? God bless you.",
  "Knock knock. Who's there? Mustache. Mustache who? Mustache you a question, but I'll shave it for later",
  "Knock knock. Who's there? Amish. Amish who? Really? You don't look like a shoe.",
  "Knock knock. Who's there? Gorilla. Gorilla who? Gorilla me a hamburger.",
  "Knock knock. Who's there? Tank. Tank who? You're welcome.",
  "Knock knock. Who's there? Turnip. Turnip who? Turnip the volume, I love this song!",
  "Knock knock. Who's there? Adore. Adore who? Adore is between us. Open up!",
  "Knock knock. Who's there? Daisy! Daisy who? Daisy me rollin, they hatin'.",
  "Knock knock. Who's there? Aida. Aida who? Aida sandwich for lunch today.",
  "Knock knock. Who's there? Cargo. Cargo who? No, car go 'beep beep'!",
  "Knock knock. Who's there? Icing. Icing who? Icing so loud, the neighbors can hear.",
  "Knock knock. Who's there? Alpaca. Alpaca who? Alpaca the trunk, you pack the suitcase.",
  "Knock knock. Who's there? Cereal. Cereal who? Cereal pleasure to meet you!",
  "Knock knock. Who's there? A little old lady. A little old lady who? Dang! All this time, I had no idea you could yodel.",
  "Knock knock. Who's there? Keith! Keith who? Keith me, my thweet preenth!",
  "Knock knock. Who's there? Lettuce. Lettuce who? Lettuce in it's cold out here.",
  "Knock knock. Who's there? Oswald. Oswald who? Oswald my bubble gum!",
  "Knock knock. Who's there? Boo. Boo who? Hey, don't cry!",
  "Knock knock. Who's there? An extraterrestrial. An extraterrestrial who? Wait, how many extraterrestrials do you know?",
  "Knock knock. Who's there? Police. Police who? Police stop telling these awful knock knock jokes!",
  "Knock knock. Who's there? Candice. Candice who? Candice door open or what?",
  "Knock knock. Who's there? Control Freak. Con— Okay, now you say, 'Control Freak who?!'",
  "Knock knock. Who's there? Theodore! Theodore who? Theodore wasn't open so I knocked.",
  "Knock knock. Who's there? Yah. Yah who? No thanks, I use Bing or Google.",
  "Knock knock. Who's there? Snow. Snow who? Snow use. I forgot my name again!",
  "Knock knock. Who's there? Robin. Robin who? Robin you, now hand over the cash!",
  "Knock knock. Who's there? Pecan! Pecan who? Pecan somebody your own size!",
  "Knock knock. Who's there? Dwayne. Dwayne who? Dwayne the bathtub already. I'm drowning!",
  "Knock knock. Who's there? Annie. Annie who? Annie way you can let me in now?",
  "Knock knock. Who's there? Cantaloupe!  Cantaloupe who? Cantaloupe to Vegas, our parents would get mad.",
  "Knock knock. Who's there? Spell. Spell who? Okay, fine. W-H-O.",
  "Knock knock. Who's there? Water. Water who? Water those plants or they're going to die!",
  "Knock knock. Who's there? Euripides. Euripides who? Euripides jeans, you pay for 'em.",
  "Knock knock. Who's there? Closure. Closure who? Closure mouth while you're chewing!",
  "Knock knock. Who's there? Cash. Cash who? No thanks, but I'd love some peanuts!",
  "Knock knock. Who's there? Olive. Olive who? Olive you and I don't care who knows it!",
  "Knock knock. Who's there? Tyrone. Tyrone who? Tyrone shoelaces!",
];

module.exports = {
  knockJokes,
};
